### ISSUE TITLE
Yana-server et Yana-android

### ISSUE THREAD

**Issue by ruf147** [ldleman/yana-server#165]
Bonsoir

J' ai deux problèmes, un concerne l'installe de yana-server et l'autre yana-android.
Après avoir installé  yana-server, j'ai ça dans les logs de lighttpd/error ;

2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  file_put_contents(/var/www/html/yana-server/dbversion): failed to open stream: Permission denied in /var/www/html/yana-server/common.php on line 33
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  file_put_contents(/var/www/html/yana-server/dbversion): failed to open stream: Permission denied in /var/www/html/yana-server/common.php on line 40
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  file_get_contents(/var/www/html/yana-server/dbversion): failed to open stream: No such file or directory in /var/www/html/yana-server/common.php on line 41
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to open database: unable to open database file' in /var/www/html/yana-server/classes/SQLiteEntity.class.php:23
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: Stack trace:
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: #0 /var/www/html/yana-server/classes/SQLiteEntity.class.php(23): SQLite3->open('/var/www/html/y...', 6)
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: #1 /var/www/html/yana-server/classes/User.class.php(29): SQLiteEntity->__construct()
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: #2 /var/www/html/yana-server/classes/Functions.class.php(231): User->__construct()
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: #3 /var/www/html/yana-server/common.php(44): Functions::alterBase(Array, false)
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: #4 /var/www/html/yana-server/header.php(2): require_once('/var/www/html/y...')
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: #5 /var/www/html/yana-server/index.php(2): require_once('/var/www/html/y...')
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr: #6 {main}
2016-01-08 23:21:52: (mod_fastcgi.c.2695) FastCGI-stderr:   thrown in /var/www/html/yana-server/classes/SQLiteEntity.class.php on line 23
2016-01-08 23:22:31: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, table `yana_device` already exists in /var/www/html/yana-server/classes/SQLiteEntity.class.php on line 371
2016-01-08 23:22:31: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, duplicate column name: state in /var/www/html/yana-server/classes/SQLiteEntity.class.php on line 371

Est-ce grave ?
Après pour yana-android, j'ai un autre souci après installation, ça m'ecris après update des commandes :
échec de compréhension par rapport à la réponse du raspberry Pi. Veuillez présenter le problème à Nover.
Il ne prend en compte aucune de mes nouvelles commande cree et Yana ne parle pas, juste le chat...
J' ai loupé quelque chose ?

**Comment by gwenoleR** [comment]
Bonjour,
Concernant le problème lighttpd je ne peux pas t'aider, par contre pour le problème de l'application Android je peux ! 
Le probleme est normal, la nouvelle version du server YANA apporte des nouvelles commandes que l'application de Nover ne prend pas en charge d'ou le message "échec de compréhension par rapport à la réponse du raspberry Pi"
Une nouvelle version beta est disponible sur le Store : https://play.google.com/store/apps/details?id=alexandreroland.yana

En espérant avoir pu aider.

**Comment by ldleman** [comment]
Tu a un soucis de permissions mal réglées pour l'erreur dbversion, essaye un 
`sudo chown -R www-data:www-data /var/www/html/yana-server

**Comment by ruf147** [comment]
ok, je m' y colle ce soir, merci a vous.

Autre bug rencontre (si c' est un bug), il m' est impossible d' installer la derniere version de yana sur mon bon vieu Nexus S...
Version d' Android : 4.1.2
Version du noyau : 3.0.31-g5894150

Appareil non supporté je pense, sinon, une idée?

C' est la seul plateforme Android que j' ai pour tester, donc si vous avez une idée, n' hesitez pas.

**Comment by gwenoleR** [comment]
Hello,
C'est normal que tu ne puisse pas installer la nouvelle application Android, d'après le PlayStore il faut en effet la version 4.4 minimum d'android pour pouvoir la telecharger.. Surement à cause des fonctionnalités lié à Android Wear pour les montres connectées..
Si tu possède un appareil Apple une mise à jour arrive pour gérer la nouvelle version du serveur.
Si tu possède un appareil WindowsPhone tu n'as plus qu'a developper l'application ou attendre patiemment qu'un membre s'y mette !

**Comment by ruf147** [comment]
Ok merci de ta réponse rapide.

**Comment by ruf147** [comment]
Merci, c'était bien un problème de droit.
Pour mon vieux Nexus, j'ai reussi à en dégoter un plus recent donc à ce niveau aussi c'est réglé.
Mais impossible de télécharger le v2 sur le store, j'ai ouvert un nouveau post et mais celui-ci comme résolue.
